`timescale 1ns/1ps
`default_nettype none
// Memory: synchronous read, word addressing via mem_addr[12:2] (6 KB =
// 1536 words), read strobe with hold while low, byte-enabled writes. Words
// 0..32 hold the SOC's demo program (UART banner + one LED walk + echo
// loop, 30 code words + 3 message words), generated by the assembler tasks
// in rtl/memory.v; the bench re-assembles the identical program with the
// lib macros and cross-checks (soc_tb.v additionally checks the words
// against hand-assembled constants). Words 33..1535 are filled by the bench
// so the whole 1536-word address space can be exercised, including writes
// above 1 KB and at the last word.
module memory_tb;
  `include "check.vh"
  `WATCHDOG(2_000_000)

  reg         clk = 0;
  reg  [31:0] mem_addr = 32'd0;
  wire [31:0] mem_rdata;
  reg         mem_rstrb = 0;
  reg  [31:0] mem_wdata = 32'd0;
  reg  [3:0]  mem_wmask = 4'b0000;

  Memory dut (.clk(clk), .mem_addr(mem_addr), .mem_rdata(mem_rdata),
              .mem_rstrb(mem_rstrb), .mem_wdata(mem_wdata), .mem_wmask(mem_wmask));

  always #10 clk = ~clk;

  // Re-assemble the ROM program (must match rtl/memory.v, including the
  // `ifdef FAST_SIM delay constant).
  reg [31:0] MEM [0:32];
  `include "riscv_assembly.v"
  integer WBYTE = 12, WBUSY = 20, LSTEP = 48, WDELAY = 60, ECHO = 80, EBUSY = 96;

  // Expected read for word w: program words 0..32, bench fill pattern above.
  function [31:0] expWord(input integer w);
    if (w < 33) expWord = MEM[w];
    else        expWord = 32'hDEAD0000 + w;
  endfunction

  integer i, k, off;

  // Assemble the program copy at t=0+1ns (the lib's `initial memPC = 0` has
  // run by then; the main sequence waits two clocks before reading).
  initial begin
    #1;
    LUI(x5, 32'h00400000);
    ADDI(x6, x0, 120);
    ADDI(x7, x0, 12);
    Label(WBYTE); LB(x10, x6, 0);
    SW(x10, x5, 8);
    Label(WBUSY); LW(x8, x5, 16);
    ANDI(x8, x8, 512);
    BNE(x8, x0, LabelRef(WBUSY));
    ADDI(x6, x6, 1);
    ADDI(x7, x7, -1);
    BNE(x7, x0, LabelRef(WBYTE));
    ADDI(x9, x0, 1);
    Label(LSTEP); SW(x9, x5, 4);
`ifdef BENCH
    ADDI(x14, x0, 2);
    ADDI(x14, x14, 0);
`else
    LUI(x14, 32'h0007A000);
    ADDI(x14, x14, 32'h120);
`endif
    Label(WDELAY); ADDI(x14, x14, -1);
    BNE(x14, x0, LabelRef(WDELAY));
    ADD(x9, x9, x9);
    ANDI(x9, x9, 31);
    BNE(x9, x0, LabelRef(LSTEP));
    Label(ECHO); LW(x8, x5, 32);
    ANDI(x11, x8, 256);
    BEQ(x11, x0, LabelRef(ECHO));
    SW(x8, x5, 8);
    Label(EBUSY); LW(x12, x5, 16);
    ANDI(x12, x12, 512);
    BNE(x12, x0, LabelRef(EBUSY));
    ANDI(x13, x8, 31);
    SW(x13, x5, 4);
    JAL(x0, LabelRef(ECHO));
    DATAB(8'h4C, 8'h6F, 8'h6F, 8'h70);   // "Loop"
    DATAB(8'h20, 8'h52, 8'h49, 8'h53);   // " RIS"
    DATAB(8'h43, 8'h2D, 8'h56, 8'h0A);   // "C-V\n"
    endASM();
  end

  // Fill words 33..1535 so the whole address space is readable (the ROM's own
  // initial block only touches 0..32, so the two cannot collide).
  initial begin
    for (i = 33; i < 1536; i = i + 1)
      dut.MEM[i] = 32'hDEAD0000 + i;
  end

  initial begin
    // Settle: t=0 initial blocks in other modules must have run before we
    // look at dut.MEM.
    repeat (2) @(posedge clk); #1;

    // The bench copy and the ROM must agree.
    for (i = 0; i < 33; i = i + 1)
      `CHECK_EQ(dut.MEM[i], MEM[i], "ROM word matches the bench's assembled copy")

    // Word addressing: byte address 4*w selects word w, over the whole
    // 1536-word (6 KB) space — including every word above 1 KB.
    for (i = 0; i < 1536; i = i + 1) begin
      mem_rstrb = 1;
      mem_addr  = i*4;
      @(posedge clk); #1;
      `CHECK_EQ(mem_rdata, expWord(i), "word read at byte address 4*w")
    end

    // Unaligned byte offsets are ignored: 4*w+1..3 read the same word.
    for (i = 0; i < 1536; i = i + 1)
      for (off = 1; off <= 3; off = off + 1) begin
        mem_addr = i*4 + off;
        @(posedge clk); #1;
        `CHECK_EQ(mem_rdata, expWord(i), "byte offset within the word is ignored")
      end

    // Address bits above [12:2] are ignored (0x4000000C is word 3 again).
    mem_addr = 32'h4000_000C;
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, expWord(3), "address bits above [12:2] are ignored")

    // Synchronous read: a new address does nothing until the next clock edge.
    // (Last read above was word 3; the edge for word 7 has not happened yet.)
    mem_addr = 32'd28;   // word 7
    #1;                  // no clock edge since the last read
    `CHECK_EQ(mem_rdata, expWord(3), "no read without a clock edge")
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, expWord(7), "read completes on the clock edge")

    // Strobe low: rdata holds across edges while the address keeps moving.
    mem_rstrb = 0;
    for (k = 0; k < 4; k = k + 1) begin
      mem_addr = k*4;
      @(posedge clk); #1;
      `CHECK_EQ(mem_rdata, expWord(7), "rdata holds when strobe is low")
    end

    // Strobe high again: the addressed word appears.
    mem_rstrb = 1;
    mem_addr  = 32'd40;  // word 10
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, expWord(10), "read resumes when strobe goes high")

    // ---- Writes above 1 KB and at the last word ----
    // SW to the very last word (byte 6140 = word 1535).
    mem_rstrb = 0;
    mem_addr  = 32'd6140;
    mem_wdata = 32'hC0DE_0FFF;
    mem_wmask = 4'b1111;
    @(posedge clk); #1;
    `CHECK_EQ(dut.MEM[1535], 32'hC0DE_0FFF, "SW commits at the last word (6 KB - 4)")

    // First word above 1 KB (byte 1024 = word 256) and the 4 KB boundary.
    mem_addr  = 32'd1024;  mem_wdata = 32'h0000_1000;  // word 256
    @(posedge clk); #1;
    mem_addr  = 32'd4096;  mem_wdata = 32'h0000_4000;  // word 1024
    @(posedge clk); #1;
    mem_wmask = 4'b0000;

    // SB/SH lane isolation above 1 KB: poison word 300 (byte 1200), then
    // patch one byte / one halfword and check the neighbours survive.
    // The bench plays the master's role: the lane is encoded in mem_wmask
    // (Memory itself ignores mem_addr[1:0] — the Processor's stMask picks it).
    mem_addr  = 32'd1200;  mem_wdata = 32'hFFFF_FFFF;  // poison word 300
    mem_wmask = 4'b1111;
    @(posedge clk); #1;
    mem_wmask = 4'b0010;   mem_wdata = 32'h5A5A_5A5A;  // SB 0x5A into lane 1
    mem_addr  = 32'd1201;
    @(posedge clk); #1;
    `CHECK_EQ(dut.MEM[300], 32'hFFFF_5AFF, "SB above 1 KB writes only its byte")
    mem_wmask = 4'b1100;   mem_wdata = 32'hBEEF_BEEF;  // SH 0xBEEF into halfword 1
    mem_addr  = 32'd1202;
    @(posedge clk); #1;
    mem_wmask = 4'b0000;
    `CHECK_EQ(dut.MEM[300], 32'hBEEF_5AFF, "SH above 1 KB writes only its halfword")
    `CHECK_EQ(dut.MEM[299], 32'hDEAD_0000 + 299, "SB/SH left the word below intact")
    `CHECK_EQ(dut.MEM[301], 32'hDEAD_0000 + 301, "SB/SH left the word above intact")

    // Read the written words back through the port.
    mem_rstrb = 1;
    mem_addr  = 32'd6140;
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, 32'hC0DE_0FFF, "last word reads back through the port")
    mem_addr  = 32'd1024;
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, 32'h0000_1000, "first word above 1 KB reads back")
    mem_addr  = 32'd4096;
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, 32'h0000_4000, "word at the 4 KB boundary reads back")
    mem_addr  = 32'd1200;
    @(posedge clk); #1;
    `CHECK_EQ(mem_rdata, 32'hBEEF_5AFF, "patched word reads back through the port")

    `DONE
  end
endmodule
`default_nettype wire
